filebeat.inputs:
  # Application logs
  - type: log
    enabled: true
    paths:
      - /logs/app-*.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      log_type: application
    fields_under_root: true

  # Nginx access logs
  - type: log
    enabled: true
    paths:
      - /nginx-logs/access.log
    fields:
      log_type: nginx-access
    fields_under_root: true

  # Nginx error logs
  - type: log
    enabled: true
    paths:
      - /nginx-logs/error.log
    fields:
      log_type: nginx-error
    fields_under_root: true

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3

# Output directly to Elasticsearch (alternative, comment out if using Logstash)
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   indices:
#     - index: "ollama-app-logs-%{+yyyy.MM.dd}"
#       when.equals:
#         log_type: "application"
#     - index: "ollama-nginx-access-%{+yyyy.MM.dd}"
#       when.equals:
#         log_type: "nginx-access"
#     - index: "ollama-nginx-error-%{+yyyy.MM.dd}"
#       when.equals:
#         log_type: "nginx-error"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~